### ISSUE TITLE
url in Template does not resolve

### ISSUE THREAD

**Issue by richardkaplan** [retorquere/devonthink#5]
url in the template does not resolve in the final HTML

**Comment by retorquere** [comment]
It does for me. Do you have a concrete sample (full path inside the `output` directory) where it does not?

**Comment by richardkaplan** [comment]
It works for me now too.  Maybe related to the other fix you did?

**Comment by retorquere** [comment]
nothing was changed that would do this. Maybe you didn't clear the output directory and you're still seeing old items?

**Comment by richardkaplan** [comment]
That is possible - I may have deleted in Devonthink but not emptied trash and in that case the directory is unchanged.

In any event works great now  - thanks!
