### ISSUE TITLE
not detecting some URLs

### ISSUE THREAD

**Issue by richardkaplan** [retorquere/devonthink#7]
Consider this item in the .json example I sent you separately:

![image](https://user-images.githubusercontent.com/6059733/61287078-25a2c980-a792-11e9-89c2-e7f20d1fcf68.png)

I am using this template:

![image](https://user-images.githubusercontent.com/6059733/61287107-305d5e80-a792-11e9-8b47-4a9161d34da8.png)

Why does the url from the json not resolve in this case in the html output?  

![image](https://user-images.githubusercontent.com/6059733/61287184-508d1d80-a792-11e9-9ce2-90ceb0850a79.png)

**Comment by retorquere** [comment]
Please post text instead of images

**Comment by retorquere** [comment]
I don't see an `url` in that JSON

**Comment by richardkaplan** [comment]
Here is the json as text.  There is a url which is not resolving in the template.  Interestingly, this item does not show a URL in Zotero.  Rather, Zotero creates the URL based on the Extra field which contains the PMID number.

```
{
      "itemType": "journalArticle",
      "volume": "43",
      "issue": "11",
      "pages": "792",
      "publicationTitle": "Developmental Medicine and Child Neurology",
      "ISSN": "0012-1622",
      "date": "Nov 2001",
      "extra": "PMID: 11730155",
      "journalAbbreviation": "Dev Med Child Neurol",
      "libraryCatalog": "PubMed",
      "language": "eng",
      "title": "'Life expectancy among people with cerebral palsy in Western Australia'",
      "creators": [
        {
          "firstName": "E.",
          "lastName": "Blair",
          "creatorType": "author"
        }
      ],
      "tags": [
        "Adult",
        "Humans",
        "Middle Aged",
        "Life Expectancy",
        "Australia",
        "Cerebral Palsy",
        "Catchment Area (Health)"
      ],
      "relations": [],
      "dateAdded": "2019-02-05T18:03:06Z",
      "dateModified": "2019-02-05T18:03:06Z",
      "uri": "http://zotero.org/users/571747/items/FCG5YBG8",
      "attachments": [
        {
          "version": 10199,
          "itemType": "attachment",
          "url": "http://www.ncbi.nlm.nih.gov/pubmed/11730155",
          "accessDate": "2019-02-05T18:03:11Z",
          "title": "PubMed entry",
          "parentItem": "FCG5YBG8",
          "linkMode": "linked_url",
          "contentType": "text/html",
          "charset": "",
          "tags": [],
          "relations": {},
          "dateAdded": "2019-02-05T18:03:11Z",
          "dateModified": "2019-02-05T18:03:11Z",
          "uri": "http://zotero.org/users/571747/items/NSLRTTJ2",
          "itemID": 30371,
          "key": "NSLRTTJ2"
        }
      ],
      "notes": [],
      "itemID": 16272,
      "citekey": "blairLifeExpectancyPeople2001a"
    },
```
This is what it looks like in Zotero - otero uses this Extra field to create the URL in format for Pubmed/ncbi:

![image](https://user-images.githubusercontent.com/6059733/61301809-b12c5280-a7b2-11e9-8a30-bc98d3a64cc7.png)

**Comment by retorquere** [comment]
That's different. The item doesn't have an URL so it doesn't show up in the template. Where does Zotero change this into a clickable URL?

**Comment by retorquere** [comment]
1.0.10 adds `attachment_url` which will be the first url found in any of the attachments.
